config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :landing_page, only: :show
  resource :quiz, only: [:new, :create]
  resource :quiz_result, only: :show

  root to: 'landing_page#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  TOTAL_QUESTIONS_ON_QUIZ = 5

  has_many :answers

  scope :personality_test, -> { preload(:answers).limit(TOTAL_QUESTIONS_ON_QUIZ) }

  def self.permitted_questions
    personality_test.pluck(:id).map { |q| "question_#{q}".to_sym }
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  def index; end
end

app/controllers/landing_page_controller.rb
# frozen_string_literal: true

class LandingPageController < ApplicationController
  def index; end
end

app/controllers/quiz_results_controller.rb
# frozen_string_literal: true

class QuizResultsController < ApplicationController
  def show
    @quiz_result = QuizResultService.call(answers_sum: session[:answers_sum])
  end
end

app/controllers/quizzes_controller.rb
# frozen_string_literal: true

class QuizzesController < ApplicationController
  def new
    @questions = Question.personality_test
  end

  def create
    session[:answers_sum] = quiz_params.values.sum(&:to_i)
    redirect_to quiz_result_path
  end

  private

  def quiz_params
    params.require(:quiz).permit(Question.permitted_questions)
  end
end

app/views/landing_page/index.html.erb
<%= render Quiz::CallToActionComponent.new do |slot| %>
  <%= slot.with_title { 'Are you an introvert or an extrovert?' } %>
  <%= slot.with_description { "Let's find out!" } %>
  <%= slot.with_link_to_new_quiz { 'Get started' } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full bg-gray-50">
  <head>
    <title>Personality Quiz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="h-full">
    <%= render Notification::FlashMessageComponent.new(flash) %>
    <div class="grid grid-cols-1 md:grid-cols-4 mt-6">
      <div></div>
      <div class="col-start-2 col-span-2"><%= yield %></div>
      <div></div>
    </div>
  </body>
</html>

app/views/quiz_results/show.html.erb
<%= render Quiz::CallToActionComponent.new do |slot| %>
  <%= slot.with_title { @quiz_result } %>
  <%= slot.with_description { 'based on your personality test score' } %>
  <%= slot.with_link_to_new_quiz { 'Want to do it again?' } %>
<% end %>

app/views/quizzes/new.html.erb
<div class="shadow sm:overflow-hidden sm:rounded-md">
  <div class="space-y-6 bg-white py-6 px-4 sm:p-6">
    <div class="py-24 px-6 sm:px-6 sm:py-32 lg:px-8">
      <div class="mx-auto max-w-2xl content-center">
        <div data-controller="quiz">
          <div>
            <h3 class="text-lg font-medium leading-6 text-gray-900" data-quiz-target="step"></h3>
          </div>

          <%= form_with(url: quiz_path, method: :post, class: 'space-y-8 divide-y divide-gray-200') do |form| %>
            <% @questions.each do |question| %>
              <div data-quiz-target="question">
                <fieldset class="mt-6">
                  <legend class="text-base font-medium text-gray-900"><%= question.title %></legend>
                  <p class="text-sm text-gray-500"></p>
                  <div class="mt-4 space-y-4">
                    <% question.answers.each do |answer| %>
                      <div class="flex items-center">
                        <%= form.radio_button "quiz[question_#{question.id}]", answer.personality, data: { action: 'quiz#enableNextButton' }, class: "h-4 w-4 border-gray-300 text-indigo-600 focus:ring-indigo-500", required: true %>
                        <%= form.label "quiz[question_#{question.id}]_#{answer.personality}", class: 'ml-3' do %>
                          <span class="block text-sm font-medium text-gray-700"><%= answer.title %></span>
                        <% end %>
                      </div>
                    <% end %>
                  </div>
                </fieldset>
              </div>
            <% end %>

            <div class="pt-5">
              <div class="flex justify-between">
                <div>
                  <button type="button" data-action="quiz#previous" data-quiz-target="previous" class="rounded-md relative inline-flex items-center border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 focus:z-10 focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500">Previous question</button>
                </div>
                <div>
                  <button type="button" data-action="quiz#next" data-quiz-target="next" class="rounded-md relative -ml-px inline-flex items-center border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 focus:z-10 focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500" disabled>Next question</button>
                </div>
              </div>
            </div>

            <div class="pt-5">
              <div class="flex justify-end">
                <%= form.submit 'Finish', 'data': { 'quiz-target': 'finish' }, class: "rounded-md inline-flex justify-center border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-600 focus:ring-offset-2" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>